#!/bin/sh
set -e

if [ "$(dpkg --status python-dev|sed -n 's/^Status: //p')" != "install ok installed" ]; then
    aptdcon --install python-dev
fi

pip -E virtualenv install -q -r requirements.txt

if [ ! -e bin ]; then
    ln -s virtualenv/bin bin
fi
