#!/bin/sh
set -e

for package in python-dev python-pip python-virtualenv; do
    if [ "$(dpkg --status -- $package|sed -n 's/^Status: //p')" != "install ok installed" ]; then
	# add a space after old values
	missing="${missing:+$missing }$package"
    fi
done
if [ -n "$missing" ]; then
    aptdcon --install $missing
fi

virtualenv virtualenv
virtualenv/bin/pip install -q -r requirements.txt

if [ ! -e bin ]; then
    ln -s virtualenv/bin bin
fi
