#!/usr/bin/python
import optparse
import subprocess
import sys

def get_refs():
    p = subprocess.Popen(
        args=[
            'git',
            'for-each-ref',
            '--format=%(objectname) %(*objectname) %(refname)',
            '--sort=-taggerdate',
            'refs/remotes/origin/',
            'refs/tags/',
            ],
        stdout=subprocess.PIPE,
        close_fds=True,
        )
    (stdout, stderr) = p.communicate()
    # TODO check p.returncode
    assert not stderr
    for line in stdout.splitlines():
        obj, tagobj, ref = line.split(' ', 2)
        if tagobj:
            obj = tagobj
        yield obj, ref

def separate_tags_and_branches(refs):
    tags = []
    branches = []
    for obj, ref in refs:
        if ref.startswith('refs/tags/'):
            tags.append((obj, ref))
        elif ref.startswith('refs/remotes/origin/'):
            branches.append((obj, ref))
        else:
            raise RuntimeError('Bad refname: %r' % ref)
    return tags, branches

PRIORITIZE = [
    'master',
    'next',
    'stable',
    ]

IGNORE = [
    'HEAD',
    'ceph-v0.20.1',
    'v0.1',
    'v0.2',
    'v0.3',
    'v0.4',
    'v0.5',
    'v0.6',
    'v0.7',
    'v0.7.1',
    'v0.7.2',
    'v0.7.3',
    'v0.8',
    'v0.9',
    'v0.10',
    'v0.11',
    'v0.12',
    'v0.13',
    'v0.14',
    'v0.15',
    'v0.16',
    'v0.16.1',
    'v0.17',
    'v0.18',
    'v0.19',
    'v0.19.1',
    'v0.20',
    'v0.20.1',
    'v0.20.2',
    'v0.21',
    'v0.21.1',
    'v0.21.2',
    'v0.21.3',
    'v0.22',
    'v0.22.1',
    'v0.22.2',
    'v0.23',
    'v0.23.1',
    'v0.23.2',
    'v0.24',
    'v0.24.1',
    'v0.24.2',
    'v0.24.3',
    'v0.25',
    'v0.25.1',
    'v0.25.2',
    'v0.26',
    'v0.27',
    'v0.27.1',
    'v0.28',
    'v0.28.1',
    'v0.28.2',
    'v0.29',
    'v0.29.1',
    'v0.30',
    'v0.31',
    'v0.32',
    'v0.33',
    'v0.34',
    'v0.35',
    'v0.36',
    'v0.37',
    'v0.38',
    'v0.39',
    'v0.40',
    'v0.41',
    'v0.42',
    'v0.42.1',
    'v0.42.2',
    'v0.43',
    'v0.44',
    'v0.44.1',
    'v0.44.2',
    ]

IGNORE_PREFIX = [
    'historic/',
    ]

def separate_priority_branches(branches):
    prioritize = ['origin/{0}'.format(b) for b in PRIORITIZE]
    ignore = ['origin/{0}'.format(b) for b in IGNORE]
    ignore_prefix = ['origin/{0}'.format(b) for b in IGNORE_PREFIX]

    priority = []
    normal = []

    for obj, ref in branches:
        if ref in prioritize:
            priority.append((obj, ref))
            continue

        if ref in ignore:
            continue

        if any(ref.startswith(prefix) for prefix in ignore_prefix):
            continue

        normal.append((obj, ref))

    # priority lost its ordering, restore it
    priority.sort(key=lambda (obj,ref): prioritize.index(ref))

    return priority, normal

def strip_prefix(refs, prefix):
    for obj, ref in refs:
        assert ref.startswith(prefix)
        ref = ref[len(prefix):]
        yield obj, ref

def doit(output, verbose):
    refs = get_refs()
    tags, branches = separate_tags_and_branches(refs)
    tags = strip_prefix(tags, 'refs/tags/')

    branches = strip_prefix(branches, 'refs/remotes/')
    priority, normal = separate_priority_branches(branches)

    ptags, normaltags = separate_priority_branches(tags)

    if verbose:
        fmt = '{0} {1}'
    else:
        fmt = '{1}'

    for l in [priority, normal, ptags, normaltags]:
        for (obj, ref) in l:
            print >>output, fmt.format(obj, ref)

def main():
    parser = optparse.OptionParser(
        usage='%prog [-v]',
        description='Output interesting git tags and branches, for gitbuilder.',
        )
    parser.add_option(
        '-v', '--verbose',
        action='store_true',
        )
    opts, args = parser.parse_args()
    if args:
        parser.error('Unexpected arguments.')

    doit(sys.stdout, opts.verbose)

if __name__ == '__main__':
    main()
