#!/bin/sh
set -e

# stdout/stderr are not yet redirected on /etc/init.d systems
exec >>logs/stdout.log 2>>logs/stderr.log

FILE_OWNER="$(stat --format='%U' gitbuilder.git/out)"
CUR_USER="$(id -un)"
if [ "$FILE_OWNER" = "root" ]; then
    echo "$0: root should never own the build tree, aborting." 1>&2
    exit 1
fi

if [ "$CUR_USER" = "root" ]; then
    # reexecute as the right user;
    # override /bin/false as shell in passwd
    echo "$0: I'm root, reexecuting as $FILE_OWNER"
    exec su -s /bin/sh -c "$0 $*" $FILE_OWNER
fi

if [ "$CUR_USER" != "$FILE_OWNER" ]; then
    echo "$0: not root and not file owner, aborting." 1>&2
    exit 1
fi

if command -v logrotate >/dev/null; then
  logrotate -v --state=logs/.logrotate.status logrotate.conf
fi

# if the log was rotated, move to the new files; if not
# nothing changes
exec >>logs/stdout.log 2>>logs/stderr.log


cd gitbuilder.git
exec ../run-real
