#!/bin/sh
set -e

logrotate --state=logs/.logrotate.status logrotate.conf
exec >>logs/stdout.log 2>>logs/stderr.log

cd gitbuilder.git
FILE_OWNER="$(stat --format='%U' out)"
CUR_USER="$(id -un)"
if [ "$FILE_OWNER" = "root" ]; then
    echo "$0: root should never own the build tree, aborting." 1>&2
    exit 1
fi

if [ "$CUR_USER" = "$FILE_OWNER" ]; then
    # we're already the right user
    exec ./autobuilder.sh
elif [ "$CUR_USER" = "root" ]; then
    # drop down to the right user
    exec su -c ./autobuilder.sh "$FILE_OWNER"
else
    echo "$0: not root and not file owner, aborting." 1>&2
    exit 1
fi
