#!/bin/sh
set -e

./autobuilder.sh

# update symlinks that make branch point to the latest successful
# tarball for that branch
MACH="$(uname -m)"
REF_TARDIR="out/tarball/ref"
install -d -m0755 -- "$REF_TARDIR"
( cd build && ../branches-local -v ) \
| while read LATEST REF; do
    # mangle unsafe characters in branch names, just in case (slashes
    # and leading periods); gitbuilder hanging on to "origin/" here
    # makes the typical result a bit ugly
    SAFE_REF="$(printf '%s' "$REF"|tr -c 'a-zA-Z0-9_.-' '_'|sed 's/^\./_/')"

    # find the latest commit in that history that we have a tar for;
    # assume it's found in the last 100 commits, to limit time wasted
    git --git-dir=build/.git rev-list --first-parent --topo-order --max-count=100 "$LATEST" \
	| while read REV; do
	TARBALL="out/tarball/sha1/$MACH.$REV.tgz"
	if [ -e "$TARBALL" ]; then
	    ln -sf -- "../sha1/$MACH.$REV.tgz" "$REF_TARDIR/$SAFE_REF.tgz"
	    break
	fi
    done
done
