#!/bin/sh
set -e

./autobuilder.sh

REF_OUTDIR="out/output/ref"
SHA_OUTDIR="out/output/sha1"

# clean up temp files from aborted runs of below symlinking; all tmp
# files are stale
find "$REF_OUTDIR" -mindepth 1 -maxdepth 1 -name '*.tmp' -print0 \
| xargs -0 --no-run-if-empty rm -f --

# update symlinks that make branch point to the latest successful
# output dir for that branch
install -d -m0755 -- "$REF_OUTDIR"
( cd build && ../branches-local -v ) \
| while read LATEST REF; do
    # mangle unsafe characters in branch names, just in case (slashes
    # and leading periods); gitbuilder hanging on to "origin/" here
    # makes the typical result a bit ugly
    SAFE_REF="$(printf '%s' "$REF"|tr -c 'a-zA-Z0-9_.-' '_'|sed 's/^\./_/')"

    # find the latest commit in that history that we have a result for;
    # assume it's found in the last 100 commits, to limit time wasted
    git --git-dir=build/.git rev-list --first-parent --topo-order --max-count=100 "$LATEST" \
	| while read REV; do
	OUTDIR="$SHA_OUTDIR"
	if [ -e "$OUTDIR" ]; then
	    ln -s -- "../sha1/$REV" "$REF_OUTDIR/$SAFE_REF.tmp"
	    mv --no-target-directory -- "$REF_OUTDIR/$SAFE_REF.tmp" "$REF_OUTDIR/$SAFE_REF"
	    break
	fi
    done
done

# remove ref symlinks that haven't been touched in 24 hours; as the above
# will always re-create the symlinks, they are guaranteed fresh
find "$REF_OUTDIR" -mindepth 1 -maxdepth 1 -mtime +0 -printf '%p\0' \
| xargs -0 --no-run-if-empty -- rm -rf --

# clean temp output dirs; since there cannot be a build running in
# parallel with us, all tmp files are stale
find "$SHA_OUTDIR" -mindepth 1 -maxdepth 1 -name '*.tmp' -print0 \
| xargs -0 --no-run-if-empty rm -rf --

# note down what sha1's are still pointed to by refs
find "$REF_OUTDIR" -mindepth 1 -maxdepth 1 -type l -printf '%l\n' >out/refs-still-alive

# and finally remove any output dir older than 24h, that is not target
# of symlink; need to do ugly things in xargs because the symlinks
# destinations are cross-directory paths
find "$SHA_OUTDIR" -mindepth 1 -maxdepth 1 -mtime +0 -printf '../sha1/%P\0' \
| grep --null-data --fixed-strings --line-regexp --invert-match --file=out/refs-still-alive \
| xargs -0 --no-run-if-empty -I '{}' -- rm -rf -- "$SHA_OUTDIR/{}"
